name: Type Check
on: 
  pull_request:
    paths:
      - '**.js'
  push:
    paths:
      - '**.js'

jobs:
  check-type:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: '**/package-lock.json'
          registry-url: https://registry.npmjs.org
      - run: npm install -D
      - run: npm install --prefix sfml-js
      - run: npm run check
